### ISSUE TITLE
Getting a ValueError, start is greater than end in cleavage-profile.

### ISSUE THREAD

**Issue by ravibandaru-lab** [epifluidlab/FinaleToolkit#115]
Hey James. 

For this error, feel free to log into PSC and cd to `/ocean/projects/mcb190124/rbandaru/finaletoolkit-figures/3E/` and run the following command to reproduce this error.

_finaletoolkit cleavage-profile -q 30 -lo 50 -hi 512 -w 128 ../data/BH01.hg19.frag.bed.gz ../outputs/3E/ctcf_intervals.bed ../outputs/3E/ctcf.cleavageprop.bw ../data/hg19.chrom.sizes_ 

### I switched to the ravi branch and ran the following VVV and it worked perfectly, if this helps you debug, 

_finaletools cleavage-profile -w 128 -min 50 -max 512 -c ../data/hg19.chrom.sizes ../data/BH01.hg19.frag.bed.gz ../outputs/3E/ctcf_intervals.bed ../outputs/ctcf.cleavageprop.bw_

**ERROR MESAGE**

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/jet/home/rbandaru/.conda/envs/bert/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/jet/home/rbandaru/.conda/envs/bert/lib/python3.11/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "/jet/home/rbandaru/.conda/envs/bert/lib/python3.11/site-packages/finaletoolkit/frag/cleavage_profile.py", line 144, in _cleavage_profile_star
    return cleavage_profile(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/rbandaru/.conda/envs/bert/lib/python3.11/site-packages/finaletoolkit/frag/cleavage_profile.py", line 92, in cleavage_profile
    frags = frag_array(
            ^^^^^^^^^^^
  File "/jet/home/rbandaru/.conda/envs/bert/lib/python3.11/site-packages/finaletoolkit/utils/utils.py", line 425, in frag_array
    frag_list = [
                ^
  File "/jet/home/rbandaru/.conda/envs/bert/lib/python3.11/site-packages/finaletoolkit/utils/utils.py", line 425, in <listcomp>
    frag_list = [
                ^
  File "/jet/home/rbandaru/.conda/envs/bert/lib/python3.11/site-packages/finaletoolkit/utils/utils.py", line 346, in frag_generator
    for line in tbx.fetch(
                ^^^^^^^^^^
  File "pysam/libctabix.pyx", line 457, in pysam.libctabix.TabixFile.fetch
ValueError: start (250317696) >= end (249250621)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/jet/home/rbandaru/.conda/envs/bert/bin/finaletoolkit", line 8, in <module>
    sys.exit(main_cli())
             ^^^^^^^^^^
  File "/jet/home/rbandaru/.conda/envs/bert/lib/python3.11/site-packages/finaletoolkit/cli/main_cli.py", line 813, in main_cli
    function(**funcargs)
  File "/jet/home/rbandaru/.conda/envs/bert/lib/python3.11/site-packages/finaletoolkit/frag/cleavage_profile.py", line 263, in _cli_cleavage_profile
    for interval_score in interval_scores:
  File "/jet/home/rbandaru/.conda/envs/bert/lib/python3.11/multiprocessing/pool.py", line 423, in <genexpr>
    return (item for chunk in result for item in chunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/rbandaru/.conda/envs/bert/lib/python3.11/multiprocessing/pool.py", line 873, in next
    raise value
ValueError: start (250317696) >= end (249250621)
```

**Comment by jamesli124** [comment]
This issue will be fixed in the release version of 0.8.0. You can try the following command once that is out:
`finaletoolkit cleavage-profile -w 128 -min 50 -max 512 -o ../outputs/ctcf.cleavageprop.bw -c ../data/b37.chrom.sizes ../data/BH01.hg19.frag.bed.gz ../outputs/ctcf_intervals.bed`
